# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 04:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
