# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 02:18
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160106_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(default=None, upload_to=blog.models.get_upload_file_name),
        ),
    ]
