# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160107_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='user',
        ),
        migrations.AddField(
            model_name='authors',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='authors',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authors',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authors',
            name='username',
            field=models.CharField(default='user', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
