# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160107_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
