# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_authors_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
